# Generated by Django 5.0.2 on 2024-07-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_livro_categoria_livro_editora"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autor",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="autores", to="core.autor"
            ),
            preserve_default=False,
        ),
    ]
