# Generated by Django 5.0.2 on 2024-08-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_livro_autor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="autor",
        ),
    ]
