# Generated by Django 5.0.2 on 2024-08-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_livro_autor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
    ]
