# Generated by Django 5.0.2 on 2024-08-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_autor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="autor",
            field=models.ManyToManyField(blank=True, null=True, related_name="autores", to="core.autor"),
        ),
    ]
