# Generated by Django 5.0.2 on 2024-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_editora_email_editora_pais"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editora",
            name="pais",
        ),
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="editora",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="editora",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
